name: Release Drafter
# Run action on push in mater branch
on:
  push:
    branches:
    - master

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
    # Create/Update release draft
    - uses: release-drafter/release-drafter@v5.12.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
